## Ridge & Lasso Regression 

### bodyfat dataset

In [1]:
import os
import pandas as pd


import numpy as np

In [2]:
df=pd.read_csv("C:/Users/Pooja Kathe/Desktop/linear_regression dataset/Ridge & Lasso practice dataset/bodyfat.csv")

In [3]:
df.head()

Bodyfat  Age  Weight  Height  Neck  Chest  Abdomen  Ankle  Biceps  Wrist
0     32.3   41  247.25   73.50  42.1  117.0    115.6   26.3    37.3   19.7
1     22.5   31  177.25   71.50  36.2  101.1     92.4   24.6    30.1   18.2
2     22.0   42  156.25   69.00  35.5   97.8     86.0   24.0    31.2   17.4
3     12.3   23  154.25   67.75  36.2   93.1     85.2   21.9    32.0   17.1
4     20.5   46  177.00   70.00  37.2   99.7     95.6   22.5    29.1   17.7

In [4]:
from sklearn.linear_model import LinearRegression
LinReg=LinearRegression()

In [5]:
LinReg.fit(df.iloc[:,1:11],   df.iloc[:,0])

LinearRegression()

In [7]:
from sklearn.linear_model import Lasso
LasReg=Lasso()
LasReg.fit(df.iloc[:,1:11],   df.iloc[:,0])

Lasso()

In [8]:
from sklearn.linear_model import Ridge
RidReg=Ridge()
RidReg.fit(df.iloc[:,1:11],   df.iloc[:,0])

Ridge()

In [10]:
pred_lin=LinReg.predict(df.iloc[:     ,1:11]  )
pred_las=LasReg.predict(df.iloc[:     ,1:11]  )
pred_rid=RidReg.predict(df.iloc[:     ,1:11]  )

In [11]:
import numpy as np

In [17]:
mse_lin=np.mean(np.square(df.iloc[: , 0]  - pred_lin))
mse_las=np.mean(np.square(df.iloc[: , 0]  - pred_las))
mse_rid=np.mean(np.square(df.iloc[: , 0]  - pred_rid))

In [18]:
mse_lin

15.39226932131734

In [19]:
mse_las

17.03728120220529

In [20]:
mse_rid

15.394055199660782

In [21]:
LinReg.coef_

array([ 8.37793344e-02, -8.33221931e-02,  3.59322556e-02,  1.12299488e-03,
       -1.38741586e-01,  1.03274094e+00,  2.25942608e-01,  1.48276392e-01,
       -2.20339906e+00])

In [22]:
LasReg.coef_

array([ 0.01459462, -0.13525194, -0.        , -0.        , -0.        ,
        0.96688777, -0.        ,  0.        , -0.        ])

In [23]:
RidReg.coef_

array([ 0.08163352, -0.08421588,  0.03312492, -0.01323566, -0.13683971,
        1.0327911 ,  0.20932576,  0.14674991, -2.12104621])

In [24]:
coef_df=pd.DataFrame({"Linear": LinReg.coef_  ,"Ridge"  :RidReg.coef_ ,"Lasso": LasReg.coef_})

In [25]:
coef_df

Linear     Ridge     Lasso
0  0.083779  0.081634  0.014595
1 -0.083322 -0.084216 -0.135252
2  0.035932  0.033125 -0.000000
3  0.001123 -0.013236 -0.000000
4 -0.138742 -0.136840 -0.000000
5  1.032741  1.032791  0.966888
6  0.225943  0.209326 -0.000000
7  0.148276  0.146750  0.000000
8 -2.203399 -2.121046 -0.000000

we see hear some coeffient in lasso are 0 (beta value in the lasso regressiion are shrink so it get reduse the impact fo X on Y so,actual abd predicted not far away from each other,so error also reduce ) so LASSO slove the problem of multicoliearity and overfitting

## feature selection

In [12]:
cr.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [13]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [14]:
cr.shape

(981, 13)

In [15]:
cr=cr.iloc[:,1:13]         ## remove 1st column
cr=cr.dropna()

In [16]:
cr.Gender.replace({"Male" :1 , "Female":0} ,inplace = True)
cr.Married.replace({"No" :0 , "Yes":1} , inplace = True)
cr.Education.replace({"Graduate" :1  , "Not Graduate":0} , inplace = True)
cr.Self_Employed.replace({"No":0 , "Yes" :1 }, inplace = True)
cr.Property_Area.replace({"Semiurban" :1 ,"Urban": 2 , "Rural" :3} , inplace = True)
cr.Loan_Status.replace({"Y" :1 , "N" : 0}, inplace = True)

In [17]:
cr_x=cr.iloc[:,0:11]
cr_y=cr.iloc[:,-1]

In [18]:
cr_x1=cr_x

In [20]:
cr_x = np.array(cr_x)
cr_y = np.array(cr_y)

In [21]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [24]:
from boruta import BorutaPy

In [23]:
! pip install boruta

In [26]:
boruta_feature_selector = BorutaPy(rfc,  max_iter = 25,  verbose=2)
boruta_feature_selector.fit(cr_x , cr_y )

Iteration: 	1 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	2 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	3 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	4 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	5 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	6 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	7 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	8 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	9 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	10 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	11 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	12 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	13 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	14 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	15 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	16 / 25
Confirmed: 	2
Tentative: 	1
Rejected: 	8
Iteration: 	17 / 25
Confir

BorutaPy(estimator=RandomForestClassifier(n_estimators=1000,
                                          random_state=RandomState(MT19937) at 0x226A3F84340),
         max_iter=25, random_state=RandomState(MT19937) at 0x226A3F84340,
         verbose=2)

In [27]:
boruta_feature_selector.support_

array([False, False, False, False, False,  True, False,  True, False,
        True, False])

In [32]:
cr_x1.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [33]:
feature_imp=pd.DataFrame({"feature": cr_x1.columns, "Importance":  boruta_feature_selector.support_})

In [34]:
feature_imp.sort_values("Importance",ascending=False)

feature  Importance
5     ApplicantIncome        True
7          LoanAmount        True
9      Credit_History        True
0              Gender       False
1             Married       False
2          Dependents       False
3           Education       False
4       Self_Employed       False
6   CoapplicantIncome       False
8    Loan_Amount_Term       False
10      Property_Area       False

## RFE (Recursive feature selection)

In [36]:
cr=pd.read_csv("C:/Users/Pooja Kathe/Desktop/linear_regression dataset/CreditRisk.csv")

In [37]:
cr=cr.iloc[:,1:13]         ## remove 1st column
cr=cr.dropna()

In [38]:
cr.Gender.replace({"Male" :1 , "Female":0} ,inplace = True)
cr.Married.replace({"No" :0 , "Yes":1} , inplace = True)
cr.Education.replace({"Graduate" :1  , "Not Graduate":0} , inplace = True)
cr.Self_Employed.replace({"No":0 , "Yes" :1 }, inplace = True)
cr.Property_Area.replace({"Semiurban" :1 ,"Urban": 2 , "Rural" :3} , inplace = True)
cr.Loan_Status.replace({"Y" :1 , "N" : 0}, inplace = True)
cr_x=cr.iloc[:,0:11]
cr_y=cr.iloc[:,-1]

In [35]:
from sklearn.feature_selection import RFE

In [40]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [41]:
rfe=RFE(dt,5)

C:\Users\Pooja Kathe\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass n_features_to_select=5 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [42]:
rfe.fit(cr_x,cr_y)

RFE(estimator=DecisionTreeClassifier(), n_features_to_select=5)

In [43]:
rfe.support_

array([False,  True, False, False, False,  True,  True,  True, False,
        True, False])

In [46]:
feature_imp=pd.DataFrame({"feature": cr_x.columns, "Importance":  rfe.support_})

In [47]:
feature_imp.sort_values("Importance",ascending=False)

feature  Importance
1             Married        True
5     ApplicantIncome        True
6   CoapplicantIncome        True
7          LoanAmount        True
9      Credit_History        True
0              Gender       False
2          Dependents       False
3           Education       False
4       Self_Employed       False
8    Loan_Amount_Term       False
10      Property_Area       False